language: java
jdk:
- oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

stages:
- compile
- static_code_analysis
- name: snapshot
  if: branch = master
- name: release
  if: branch = release

jobs:
  include:
  - stage: compile
    script:
    - "./gradlew compileJava compileTestJava"
  - stage: static_code_analysis
    script:
    - "./gradlew check"
  - stage: snapshot
    script:
    - "./gradlew artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER"
  - stage: release
    script:
    - "./gradlew bintrayUpload -x test bintrayPublish -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY"
